/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('states').del()
    await knex('states').insert([
        { state_abrv: "AL" },
        { state_abrv: "AK" },
        { state_abrv: "AZ" },
        { state_abrv: "AR" },
        { state_abrv: "CA" },
        { state_abrv: "CO" },
        { state_abrv: "CT" },
        { state_abrv: "DE" },
        { state_abrv: "FL" },
        { state_abrv: "GA" },
        { state_abrv: "HI" },
        { state_abrv: "ID" },
        { state_abrv: "IL" },
        { state_abrv: "IN" },
        { state_abrv: "IA" },
        { state_abrv: "KS" },
        { state_abrv: "KY" },
        { state_abrv: "LA" },
        { state_abrv: "ME" },
        { state_abrv: "MD" },
        { state_abrv: "MA" },
        { state_abrv: "MI" },
        { state_abrv: "MN" },
        { state_abrv: "MS" },
        { state_abrv: "MO" },
        { state_abrv: "MT" },
        { state_abrv: "NE" },
        { state_abrv: "NV" },
        { state_abrv: "NH" },
        { state_abrv: "NJ" },
        { state_abrv: "NM" },
        { state_abrv: "NY" },
        { state_abrv: "NC" },
        { state_abrv: "ND" },
        { state_abrv: "OH" },
        { state_abrv: "OK" },
        { state_abrv: "OR" },
        { state_abrv: "PA" },
        { state_abrv: "RI" },
        { state_abrv: "SC" },
        { state_abrv: "SD" },
        { state_abrv: "TN" },
        { state_abrv: "TX" },
        { state_abrv: "UT" },
        { state_abrv: "VT" },
        { state_abrv: "VA" },
        { state_abrv: "WA" },
        { state_abrv: "WV" },
        { state_abrv: "WI" },
        { state_abrv: "WY" },
    ]);
};